### ISSUE TITLE
Breaks typescript2 plugin

### ISSUE THREAD

**Issue by jirutka** [PepsRyuu/rollup-plugin-node-license#1]
When I add this plugin into my Rollup config, it breaks the build:

```
[!] (plugin rpt2) Error: Unknown object type "asyncfunction"
src/index.ts
Error: Unknown object type "asyncfunction"
    at Object._object (./node_modules/rollup-plugin-typescript2/node_modules/object-hash/index.js:218:17)
    at Object._function (./node_modules/rollup-plugin-typescript2/node_modules/object-hash/index.js:319:14)
    at Object.dispatch (./node_modules/rollup-plugin-typescript2/node_modules/object-hash/index.js:185:30)
    at ./node_modules/rollup-plugin-typescript2/node_modules/object-hash/index.js:246:18
    at Array.forEach (<anonymous>)
    at Object._object (./node_modules/rollup-plugin-typescript2/node_modules/object-hash/index.js:242:21)
    at Object.dispatch (./node_modules/rollup-plugin-typescript2/node_modules/object-hash/index.js:185:30)
    at ./node_modules/rollup-plugin-typescript2/node_modules/object-hash/index.js:260:23
    at Array.forEach (<anonymous>)
    at Object._array (./node_modules/rollup-plugin-typescript2/node_modules/object-hash/index.js:259:20)
```

rpt2 plugin is [rollup-plugin-typescript2](https://github.com/ezolenko/rollup-plugin-typescript2). I have another 6 plugins in the config and this problem causes only rollup-plugin-node-license.

* * *
* node 10.16.0
* rollup 1.25.2
* rollup-plugin-node-license 0.0.4
* rollup-plugin-typescript2 0.24.3

**Comment by PepsRyuu** [comment]
It looks like ```rollup-plugin-typescript2``` doesn't like the following line of code in ```rollup-plugin-node-license```: 

```renderChunk: async (code) => {```

In my opinion, this is a bug in ```rollup-plugin-typescript2```, as this is perfectly standard JavaScript, and if another plugin was also to use an async function for a plugin, it would have the same problem. 

This appears to be a known issue though with the plugin thankfully: https://github.com/ezolenko/rollup-plugin-typescript2/blob/master/README.md#compatibility See ```objectHashIgnoreUnknownHack``` where it's specifically designed for the problem of plugins using async/await.

Hope this helps! :)

**Comment by jirutka** [comment]
It’s a shame that I didn’t check `rollup-plugin-typescript2`’s Readme myself. :man_facepalming: Thanks for your help!
